using UnityEngine;

public class AutoGeneratedNavMeshSurfaceInfo : MonoBehaviour
{
    public int SourceInstanceId { get; private set; }
    public string SourceObjectName { get; private set; }

    public void Initialize(GameObject sourceObject)
    {
        if (sourceObject == null)
        {
            SourceInstanceId = 0;
            SourceObjectName = "";
            return;
        }

        SourceInstanceId = sourceObject.GetInstanceID();
        SourceObjectName = sourceObject.name;
    }
}
